server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://rm-bp1c7o760p1eyn0czfo.mysql.rds.aliyuncs.com:3306/seata_test_order?useUnicode=true&characterEncoding=utf-8
    username: hushuai
    password: Hs19910521
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alibaba:
      seata:
        # Seata 事务组名称，对应file.conf文件中 vgroup_mapping.order-service-group
        tx-service-group: order-service-group

logging:
  level:
#    root: debug
    com.oujh.seatetest.seatademo.mapper: debug    # 日志打印sql